# Header
menu:
  首页:
  分类: /categories
  标签: /tags
  归档: /archives
  RSS: /atom.xml

# qq
qq: false
qqUrl: "https://qq.com"
# twitter
twitter: false
twitterUrl: "https://twitter.com/"
# Github
Github: true
GithubUrl: "https://github.com/"
# WeiBo
WeiBo: false
WeiBoUrl: "http://weibo.com/"

# comment 以下评论内容配置到项目根目录的_config.yml中
#disqus: false
#disqus_shortname: fanyun
#gentie: false
#gentie_productKey: e80a87a6469742edbbd8b8e261f80fd2
#changyan: true
#changyan_appid: cyt2bSDmQ
#changyan_conf: prod_324e46dfa6304f2e4f0b21dadfcc62cd


#建站时间
station_time: 2016
# Content
description: haha
# 声明
declaration: 本站部分内容收集于互联网，如果有侵权内容、不妥之处，请联系我们删除。敬请谅解!
